import { readFileSync } from 'node:fs';
export const PUMP='6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
const idl=JSON.parse(readFileSync(new URL('./vendor/pump.json',import.meta.url),'utf8'));
const migration=Buffer.from(idl.events.find(e=>e.name==='CompletePumpAmmMigrationEvent').discriminator);
const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function base58(bytes){let n=BigInt('0x'+Buffer.from(bytes).toString('hex'));let out='';while(n){out=alphabet[Number(n%58n)]+out;n/=58n;}for(const b of bytes){if(b!==0)break;out='1'+out;}return out;}
export function decodeMigration(logs){const stack=[];for(const line of logs??[]){const invoke=line.match(/^Program (\w+) invoke/);if(invoke){stack.push(invoke[1]);continue;}if(/^Program \w+ (success|failed)/.test(line)){stack.pop();continue;}if(stack.at(-1)!==PUMP||!line.startsWith('Program data: '))continue;const b=Buffer.from(line.slice(14),'base64');if(b.length<200||!b.subarray(0,8).equals(migration))continue;const at=Number(b.readBigInt64LE(128))*1000;return {ca:base58(b.subarray(40,72)),pool:base58(b.subarray(136,168)),graduatedAt:at};}return null;}
export async function jsonFetch(url,options={}){const res=await fetch(url,{...options,signal:options.signal??AbortSignal.timeout(20000)});if(!res.ok){const error=new Error(`数据源返回 HTTP ${res.status}`);error.status=res.status;error.retryAfter=Number(res.headers.get('retry-after')||60);throw error;}return res.json();}
export function helius(key){const url=`https://mainnet.helius-rpc.com/?api-key=${encodeURIComponent(key)}`;return async(method,params)=>{const j=await jsonFetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(j.error)throw Error(`Helius ${method} 错误 ${j.error.code}`);return j.result;};}
export async function dexBatch(tokens){if(!tokens.length)return [];return jsonFetch('https://api.dexscreener.com/tokens/v1/solana/'+tokens.map(t=>t.ca).join(','));}
export async function recentX(bearer,t,query,maxResults){const url=new URL('https://api.x.com/2/tweets/search/recent');url.searchParams.set('query',query);url.searchParams.set('max_results',String(maxResults));url.searchParams.set('tweet.fields','created_at,author_id,entities,referenced_tweets');url.searchParams.set('sort_order','recency');if(t.xNext)url.searchParams.set('next_token',t.xNext);if(t.xSince)url.searchParams.set('since_id',t.xSince);else url.searchParams.set('start_time',new Date(t.xWindowStart??t.enrolledAt).toISOString());return jsonFetch(url,{headers:{Authorization:`Bearer ${bearer}`}});}
export async function holders(rpc,mint,maxPages=10){const owners=new Set();let cursor;for(let i=0;i<maxPages;i++){const j=await rpc('getTokenAccounts',{mint,limit:1000,...(cursor?{cursor}:{}),options:{showZeroBalance:false}});for(const a of j.token_accounts??[])if(BigInt(a.amount??0)>0n)owners.add(a.owner);if(!j.cursor||j.cursor===cursor||(j.token_accounts??[]).length<1000)return {count:owners.size,complete:true};cursor=j.cursor;}return {count:null,complete:false};}
export function parseEnhanced(tx,graduations){if(tx.transactionError||tx.type!=='SWAP')return [];const s=tx.events?.swap;if(!s)return [];const input=s.nativeInput,output=s.nativeOutput;const buys=s.tokenOutputs??[],sells=s.tokenInputs??[];const side=input&&buys.length===1&&sells.length===0?'buy':output&&sells.length===1&&buys.length===0?'sell':null;if(!side)return [];const tok=side==='buy'?buys[0]:sells[0];const native=side==='buy'?input:output;const qty=Number(tok.rawTokenAmount?.tokenAmount)/10**Number(tok.rawTokenAmount?.decimals);const wallet=native.account;if(!wallet||tok.userAccount!==wallet||!Number.isFinite(qty)||qty<=0)return [];const fee=(tx.feePayer===wallet?Number(tx.fee||0):0)/1e9;const sol=Number(native.amount)/1e9+(side==='buy'?fee:-fee);if(sol<=0)return [];return [{id:tx.signature,wallet,ca:tok.mint,at:tx.timestamp*1000,side,quantity:qty,sol,graduatedAt:graduations.get(tok.mint)??0,complete:true}];}
