import {dexBatch} from './providers.mjs';
export const SOL_MINT='So11111111111111111111111111111111111111112';
const SPL='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',TOKEN22='TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
export function mintFee(account,epoch){const v=account?.value,info=v?.data?.parsed?.info;if(![SPL,TOKEN22].includes(v?.owner)||!info||!Number.isInteger(info.decimals))throw Error('无法读取 mint 税费');const extensions=info.extensions??[];if(extensions.some(e=>!['transferFeeConfig','metadataPointer','tokenMetadata','mintCloseAuthority'].includes(e.extension)))throw Error('存在尚未支持的代币扩展');const config=extensions.find(e=>e.extension==='transferFeeConfig')?.state;if(!config)return {bps:0,maxFee:0,decimals:info.decimals};const f=Number(config.newerTransferFee?.epoch)<=epoch?config.newerTransferFee:config.olderTransferFee;const bps=Number(f?.transferFeeBasisPoints),maxFee=Number(f?.maximumFee)/10**info.decimals;if(!Number.isInteger(bps)||bps<0||bps>10000||!Number.isFinite(maxFee)||maxFee<0)throw Error('转账税费无效');return {bps,maxFee,decimals:info.decimals};}
export class Valuation{
 constructor(w){this.w=w;this.s=w.s;this.next=0;this.s.db.exec("CREATE INDEX IF NOT EXISTS fx_lookup ON records(kind,json_extract(data,'$.mint'),json_extract(data,'$.at')) WHERE kind='fx'");}
 point(mint,at){const row=this.s.db.prepare("SELECT data FROM records WHERE kind='fx' AND json_extract(data,'$.mint')=? AND json_extract(data,'$.at')<=? AND json_extract(data,'$.at')>=? ORDER BY json_extract(data,'$.at') DESC LIMIT 1").get(mint,at,at-120000);return row?JSON.parse(row.data):null;}
 price(mint,at){return this.point(mint,at)?.usd??null;}
 async tick(){if(this.busy||Date.now()<this.next||!this.w.rpc)return;this.busy=true;this.next=Date.now()+60000;try{const held=new Set([...this.s.all('shadow-run').filter(r=>r.status==='running').flatMap(r=>r.arms.flatMap(a=>a.positions.filter(p=>p.status==='open'||p.status==='pending').map(p=>p.ca))),...this.s.all('wallet').flatMap(w=>(w.positions??[]).filter(p=>p.remaining>0).map(p=>p.ca))]);const tokens=this.s.all('token').filter(t=>t.source==='stonk'&&(t.status!=='archived'||held.has(t.ca)));if(!tokens.length)return;const mints=[...new Set([SOL_MINT,...tokens.map(t=>t.quoteMint).filter(Boolean)])];for(let i=0;i<mints.length;i+=30){const pairs=await dexBatch(mints.slice(i,i+30).map(ca=>({ca})));for(const mint of mints.slice(i,i+30)){const p=pairs.filter(p=>p.chainId==='solana'&&p.baseToken?.address===mint&&Number(p.priceUsd)>0&&p.liquidity?.usd>0).sort((a,b)=>b.liquidity.usd-a.liquidity.usd)[0];if(p){const at=Date.now();this.s.put('fx',mint+':'+at,{mint,at,usd:Number(p.priceUsd),pool:p.pairAddress});}}}
 const epoch=(await this.w.rpc('getEpochInfo',[{commitment:'confirmed'}])).epoch;
 const refresh=tokens.filter(t=>!t.execution||t.execution.epoch!==epoch||Date.now()-t.execution.at>=240000).sort((a,b)=>(a.executionAttemptAt??0)-(b.executionAttemptAt??0)).slice(0,100);
 for(const t of tokens){if(t.execution&&t.execution.epoch!==epoch)this.s.put('token',t.ca,{...this.s.get('token',t.ca),shadowBlocked:'Epoch 变化，等待税费重新核验'});const price=this.price(t.quoteMint,Date.now());if(price&&t.execution)this.s.put('token',t.ca,{...this.s.get('token',t.ca),execution:{...t.execution,quotePriceUsd:price,priceAt:this.point(t.quoteMint,Date.now()).at}});}
 const required=[...new Set(refresh.flatMap(t=>[t.ca,t.quoteMint]).filter(Boolean))],accounts=new Map();for(let i=0;i<required.length;i+=100){const keys=required.slice(i,i+100);const result=await this.w.rpc('getMultipleAccounts',[keys,{encoding:'jsonParsed',commitment:'confirmed'}]);keys.forEach((key,n)=>accounts.set(key,{value:result.value?.[n]}));}
 for(const t of refresh){const now=Date.now();this.s.put('token',t.ca,{...this.s.get('token',t.ca),executionAttemptAt:now});try{const base=accounts.get(t.ca),quote=accounts.get(t.quoteMint);const price=this.price(t.quoteMint,now);if(!price)throw Error('等待计价资产 USD 行情');this.s.put('token',t.ca,{...this.s.get('token',t.ca),execution:{at:now,epoch,priceAt:this.point(t.quoteMint,now).at,quotePriceUsd:price,baseFee:mintFee(base,epoch),quoteFee:mintFee(quote,epoch)},shadowBlocked:null,smartCoverage:'按钱包实际余额变化统计；缺少历史汇率的样本不用于验证'});}catch(e){this.s.put('token',t.ca,{...this.s.get('token',t.ca),shadowBlocked:e.message});}}
 }finally{this.busy=false;}}
}
// Balance deltas already include transfer taxes: never deduct a guessed tax again.
export function parseStonkSwap(tx,tokens,price){if(tx.transactionError||tx.type!=='SWAP')return [];const out=[];const owners=new Set((tx.accountData??[]).flatMap(a=>(a.tokenBalanceChanges??[]).map(x=>x.userAccount)));for(const wallet of owners){if(!wallet||wallet!==tx.feePayer)continue;const balances=new Map();for(const a of tx.accountData??[])for(const x of a.tokenBalanceChanges??[]){if(x.userAccount!==wallet)continue;const n=Number(x.rawTokenAmount?.tokenAmount)/10**Number(x.rawTokenAmount?.decimals);if(Number.isFinite(n))balances.set(x.mint,(balances.get(x.mint)??0)+n);}const candidates=tokens.filter(t=>t.source==='stonk'&&balances.get(t.ca));if(candidates.length!==1)continue;const t=candidates[0],base=balances.get(t.ca);let quote=balances.get(t.quoteMint);if(t.quoteMint===SOL_MINT&&!quote){const swap=tx.events?.swap;quote=base>0&&swap?.nativeInput?.account===wallet?-Number(swap.nativeInput.amount)/1e9:base<0&&swap?.nativeOutput?.account===wallet?Number(swap.nativeOutput.amount)/1e9:null;}if(!quote||base*quote>=0)continue;if([...balances].some(([mint,n])=>n&&mint!==t.ca&&mint!==t.quoteMint))continue;const at=tx.timestamp*1000,fx=price(t.quoteMint,at),solFx=price(SOL_MINT,at),feeSol=Number(tx.fee)/1e9;const value=fx&&solFx&&Number.isFinite(feeSol)&&feeSol>=0?Math.abs(quote)*fx+(base>0?1:-1)*feeSol*solFx:null;out.push({id:tx.signature,wallet,ca:t.ca,at,side:base>0?'buy':'sell',quantity:Math.abs(base),sol:0,value,currency:'USD',quoteMint:t.quoteMint,quoteAmount:Math.abs(quote),quoteUsd:fx,feeSol,graduatedAt:t.graduatedAt,complete:value!==null&&value>0,valuation:'同期已采集汇率估算；含实际余额变化和网络费'});}return out;}
