import {PumpBackfill} from './pump-backfill.mjs';
import {xObservation,xSchedule} from '../lib/x-schedule.ts';
import {Valuation,parseStonkSwap} from './valuation.mjs';
import {StonkDiscovery,STONK_CONFIGS} from './stonk.mjs';
import {Analysis} from './analysis.mjs';
import {classifyPost} from '../lib/social.ts';
import { newToken,transition,heat,queryFor,associate,evaluateWallet } from '../lib/engine.ts';
import { PUMP,decodeMigration,helius,jsonFetch,dexBatch,dexPools,matchingPair,recentX,xWindowReady,holders,parseEnhanced } from './providers.mjs';
export class Worker {
 constructor(store,env=process.env){this.s=store;this.env=env;this.stonkOnly=env.MONITOR_SOURCE==='stonk';this.analysis=new Analysis(store,env);this.rpc=env.HELIUS_API_KEY?helius(env.HELIUS_API_KEY):null;this.status={helius:'未配置',x:'未配置',dex:'等待启动',lastTick:null};this.running=false;this.socket=null;this.xBackoff=0;this.lastMarket=0;this.lastHolders=0;this.lastResearch=0;this.holderIndex=0;this.heartbeat=0;this.pumpBackfill=new PumpBackfill(this);this.stonk=new StonkDiscovery(this);this.valuation=new Valuation(this);this.s.purgeExpired();for(const t of this.s.all('token'))if(t.xReservedCost)this.s.put('token',t.ca,{...t,xReservedCost:0});this.reassessWallets();}
 walletContext(){const trades=this.s.all('trade');return {trades,byWallet:Map.groupBy(trades,t=>t.wallet),fees:Map.groupBy(this.s.all('wallet-fee'),t=>t.wallet),grads:new Map(this.s.researchTokens().map(t=>[t.ca,t.graduatedAt])),rules:this.s.rules(),now:Date.now()};}
 reassessWallets(){const wallets=this.s.all('wallet');if(!wallets.length)return;const context=this.walletContext();for(const w of wallets)this.assess(w.address,context);this.updateSmart(context.trades);}
 async start(){if(this.running)return;this.running=true;if(this.rpc){this.connect();}if(!this.stonkOnly)this.backfillTimer=setInterval(()=>this.pumpBackfill.tick().catch(()=>{}),5000);this.xTimer=setInterval(()=>this.xPoll().catch(()=>{}),1000);this.marketTimer=setInterval(()=>this.marketTick().catch(()=>{}),5000);this.shadowTimer=setInterval(()=>{if(this.running)this.analysis.shadowTick();},5000);this.timer=setInterval(()=>this.tick().catch(()=>{}),5000);await this.tick();}
 stop(){this.running=false;clearInterval(this.timer);clearInterval(this.backfillTimer);clearInterval(this.xTimer);clearInterval(this.marketTimer);clearInterval(this.shadowTimer);this.socket?.close();this.s.event('system','采集已停止');}
 connect(){if(!this.running||!this.rpc)return;const ws=new WebSocket(`wss://mainnet.helius-rpc.com/?api-key=${encodeURIComponent(this.env.HELIUS_API_KEY)}`);this.socket=ws;this.heartbeat=Date.now();ws.onopen=()=>{this.status.helius='已连接';if(!this.stonkOnly)ws.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'logsSubscribe',params:[{mentions:[PUMP]},{commitment:'confirmed'}]}));if(this.stonk.enabled())STONK_CONFIGS.forEach((key,i)=>ws.send(JSON.stringify({jsonrpc:'2.0',id:10+i,method:'logsSubscribe',params:[{mentions:[key]},{commitment:'confirmed'}]})));if(!this.stonkOnly){this.pumpBackfill.begin();void this.pumpBackfill.tick();}};ws.onmessage=e=>{this.heartbeat=Date.now();try{const m=JSON.parse(e.data);if(m.error){this.status.helius='订阅被拒绝';ws.close();return;}const v=m.params?.result?.value;if(!v||v.err)return;const found=this.stonkOnly?null:decodeMigration(v.logs);if(found)this.enroll(found,v.signature);else if(v.logs?.some(x=>/Instruction: MigrateToCpswap/i.test(x)))this.stonk.enqueue(v.signature);}catch{this.status.helius='事件解析失败';}};ws.onerror=()=>{this.status.helius='连接错误';};ws.onclose=()=>{this.status.helius='连接断开，重试中';if(this.running)setTimeout(()=>this.connect(),10000);};}
 enroll(found,signature){if(this.stonkOnly&&found.source!=='stonk')return;const now=Date.now();if(!found.ca||found.graduatedAt>now+60000||found.graduatedAt<now-86400000)return;if(!this.s.get('token',found.ca)){this.s.put('token',found.ca,{...newToken(found.ca,found.pool,found.graduatedAt,now),source:found.source??'pump'});if(found.source!=='stonk')this.s.event('migration','发现已确认 Pump 毕业迁移',found.ca);}if(signature)this.s.put('config','migrationCursor',{signature,at:now});}
 async backfill(){if(this.stonkOnly)return;this.pumpBackfill.begin();await this.pumpBackfill.tick();}
 async addSignature(signature){if(this.stonkOnly)throw Error('已停止 Pump 监控；Stonk 毕业由自动发现核验');if(!this.rpc)throw Error('请先配置 Helius');if(!/^[1-9A-HJ-NP-Za-km-z]{80,90}$/.test(signature))throw Error('请输入有效交易签名');const tx=await this.rpc('getTransaction',[signature,{encoding:'json',maxSupportedTransactionVersion:0,commitment:'confirmed'}]);if(!tx||tx.meta?.err)throw Error('交易不存在或未成功');const found=decodeMigration(tx.meta.logMessages);if(!found)throw Error('未发现 Pump 官方迁移事件');if(Date.now()-found.graduatedAt>=86400000)throw Error('毕业已经超过 24 小时');this.enroll(found,signature);return found;}
 async tick(){if(this.busy||!this.running)return;this.busy=true;const now=Date.now();try{
  void this.valuation.tick().catch(()=>{});void this.stonk.tick().then(()=>{this.status.stonk=this.stonk.status;}).catch(()=>{this.status.stonk='Stonk 暂不可用，将重试';});const rules=this.s.rules(),tokens=this.s.all('token'),budget={reserved:tokens.reduce((sum,t)=>sum+(t.xReservedCost??0),0),cost:this.s.cost()};for(const t of tokens){const n=this.transitionToken(t,rules,now,heat(this.s.posts(t.ca),t.ca,now).authors,budget);if(n.status!==t.status)this.s.event('state',n.reason,t.ca);this.s.put('token',t.ca,n);}
  if(this.rpc&&this.socket?.readyState===1&&now-this.heartbeat>120000){this.socket.close();}
  void this.marketTick().catch(()=>{});
  if(this.rpc&&now-this.lastHolders>=60000){this.lastHolders=now;const list=this.s.all('token').filter(t=>t.status!=='archived');const t=list[this.holderIndex++%Math.max(1,list.length)];if(t){try{const h=await holders(this.rpc,t.ca);this.s.put('token',t.ca,{...this.s.get('token',t.ca),holders:h.count,holdersAt:now});}catch{this.s.event('data','Holders 获取失败，保留旧数据',t.ca);}}}
  void this.xPoll().catch(()=>{});
  if(now-this.lastResearch>60000){this.lastResearch=now;this.reassessWallets();if(this.rpc){if(this.env.ENABLE_WALLET_RESEARCH==='true'){try{await this.researchTick();}catch{this.s.event('data','钱包样本发现失败，继续已有钱包核验');}}await this.walletQueueTick();}}
  this.analysis.shadowTick();this.s.purgeExpired();void this.analysis.tick().catch(()=>{});this.status.lastTick=now;
 }catch(e){this.s.event('error',e.message);}finally{this.busy=false;}}
 transitionToken(t,rules,now,authors,budget=null){const reserved=budget?.reserved??this.s.all('token').reduce((sum,t)=>sum+(t.xReservedCost??0),0);const next=transition({...t,cost:Math.max(0,t.cost-(t.xReservedCost??0))},rules,now,Math.max(0,(budget?.cost??this.s.cost())-reserved),authors);return {...next,cost:t.cost};}
 async marketTick(){if(!this.running||this.marketBusy)return;this.marketBusy=true;try{const fast=Date.now()-this.lastMarket<30000;if(!fast)this.lastMarket=Date.now();await this.market(fast);if(this.running)this.analysis.shadowTick();}finally{this.marketBusy=false;}}
 async market(fast=false){
  const active=this.s.get('config','shadow-active'),run=active&&this.s.get('shadow-run',active.id);
  const held=new Set((run?.arms??[]).flatMap(a=>a.positions.filter(p=>['open','pending'].includes(p.status)).map(p=>p.ca)));
  const all=this.s.all('token');const list=fast?all.filter(t=>held.has(t.ca)&&Date.now()-(t.marketCheckedAt??0)>=5000).sort((a,b)=>(a.marketCheckedAt??0)-(b.marketCheckedAt??0)).slice(0,30):all.filter(t=>held.has(t.ca)||(t.status!=='archived'&&(t.status!=='sleeping'||!t.marketCheckedAt||Date.now()-t.marketCheckedAt>=120000)));if(!list.length)return;
  let updated=0,missing=0,officialBudget=2;
  for(let i=0;i<list.length;i+=30){const batch=list.slice(i,i+30);let pairs=[],batchError=false;try{pairs=await dexBatch(batch);if(!Array.isArray(pairs))throw Error('invalid');}catch{pairs=[];batchError=true;}
   const fallback=batch.filter(t=>{const p=matchingPair(pairs,t);return (!p||!Number.isFinite(p.fdv)||!Number.isFinite(p.liquidity?.usd));});
   let direct=[];if(fallback.length){for(const t of fallback)this.s.put('token',t.ca,{...this.s.get('token',t.ca),poolLookupAt:Date.now()});try{direct=await dexPools(fallback);}catch{batchError=true;}}
   for(const t of batch){let p=matchingPair(direct,t)??matchingPair(pairs,t);const now=Date.now(),prev=this.s.get('token',t.ca);if((!p||!Number.isFinite(p.fdv)||!Number.isFinite(p.liquidity?.usd))&&t.source==='stonk'&&officialBudget>0&&now-(prev.stonkMarketAttemptAt??0)>=60000){officialBudget--;this.s.put('token',t.ca,{...prev,stonkMarketAttemptAt:now});prev.stonkMarketAttemptAt=now;try{p=await this.stonk.marketPair(t)??p;}catch{batchError=true;}}
    const valid=p&&Number.isFinite(p.fdv)&&p.fdv>=0&&Number.isFinite(p.liquidity?.usd)&&p.liquidity.usd>=0;
    const error=valid?null:batchError?'行情接口请求失败':p?'行情源缺少 FDV 或 LP':'行情源未返回迁移池';
    if(error&&error!==prev.marketError)this.s.event('data',error+'；暂停该币 X 搜索',t.ca);
    if(!valid){missing++;this.s.put('token',t.ca,{...this.s.get('token',t.ca),marketCheckedAt:now,marketError:error});continue;}
    const account=p.info?.socials?.find(s=>s.type==='twitter')?.url?.match(/^https:\/\/(?:www\.)?(?:x|twitter)\.com\/([A-Za-z0-9_]{1,15})(?:[/?#]|$)/)?.[1]??null;
    const fdv=p.fdv,meaningful=prev.fdv>0&&fdv/prev.fdv>=1.05,authors=heat(this.s.posts(t.ca),t.ca,now).authors;
    const value={...this.s.get('token',t.ca),symbol:p.baseToken.symbol??prev.symbol,name:p.baseToken.name??prev.name,priceUsd:Number(p.priceUsd)>0?Number(p.priceUsd):null,fdv,lp:p.liquidity.usd,marketAt:p._at??now,marketCheckedAt:now,marketError:null,marketSource:p._source??(matchingPair(direct,t)?'DexScreener 迁移池直查':'DexScreener CA 批查'),xAccount:prev.xAccount??account,lastSignalAt:meaningful?now:prev.lastSignalAt,history:[...prev.history,{at:now,fdv,authors}].slice(-2880)};
    const next=this.transitionToken(value,this.s.rules(),now,authors);if(next.status!==prev.status)this.s.event('state',next.reason,t.ca);this.s.put('token',t.ca,next);updated++;
   }
  }
  if(list.length)this.status.dex=missing?'行情不完整 · 更新 '+updated+' / 缺失 '+missing:'已连接 · 行情已更新';
 }
 resumeX(){this.s.put('config','x-block',null);this.xBackoff=0;this.xDispatchAt=0;this.status.x='等待重新验证';this.s.event('x','已手动恢复 X 请求；下一次采集将验证认证和参数');}
 async xPoll(){if(this.xBusy||Date.now()<(this.xDispatchAt??0)+2000)return;this.xBusy=true;this.xDispatchAt=Date.now();try{await this.xPollInner();if(this.running)this.analysis.shadowTick();}finally{this.xBusy=false;}}
 async xPollInner(){const s=this.s,r=s.rules(),now=Date.now();if(!this.env.X_BEARER_TOKEN){this.status.x='未配置';return;}if(this.env.ENABLE_X!=='true'){this.status.x='已配置 · 付费采集未开启';return;}const block=s.get('config','x-block');if(block){this.status.x=block.message;return;}if(!this.running||now<this.xBackoff)return;const schedule=xSchedule(s.all('token').filter(t=>now-t.graduatedAt<Math.min(24,r.maxAgeHours)*3600000),now,r.lowFdv).slice(0,r.maxActive);const list=schedule.map(x=>x.token);const selected=schedule.find(x=>x.due<=now&&xWindowReady(x.token,now));const t=selected?.token;if(!t){this.status.x=list.some(t=>!xWindowReady(t,now))?'等待 X 搜索窗口（入监控后至少 45 秒）':'等待下一次采集';return;}
  // Reserve the maximum possible response cost before calling the paid API.
  const remaining=Math.min(r.dailyBudget-s.cost(),r.tokenBudget-t.cost);const max=Math.min(100,Math.floor((remaining+1e-9)/r.postPrice));if(max<10){s.put('token',t.ca,{...t,status:'sleeping',reason:'剩余预算不足一次最小请求',stateAt:now});return;}
  s.put('token',t.ca,{...t,xLastPoll:now,xPollIntervalMs:selected.interval,xPollTier:selected.tier});const reserveId=`request:${now}:${t.ca}`;s.charge(reserveId,max*r.postPrice,now);s.put('token',t.ca,{...s.get('token',t.ca),cost:t.cost+max*r.postPrice,xReservedCost:max*r.postPrice});
  try{const j=await recentX(this.env.X_BEARER_TOKEN,t,queryFor(t),max);const receivedAt=Date.now();let uniqueCost=0;const before=s.posts(t.ca);const normalized=text=>text.toLowerCase().replace(/https?:\/\/\S+/g,'').replace(/[\s\p{P}]+/gu,' ').trim();const templates=new Set(before.map(p=>normalized(p.text)));const currentAuthors=new Set();for(const p of j.data??[]){const at=Date.parse(p.created_at);if(!Number.isFinite(at))continue;const text=p.text+' '+(p.entities?.urls??[]).map(u=>u.expanded_url??u.url).join(' ');const charge=s.charge(p.id,r.postPrice,now);if(charge)uniqueCost+=r.postPrice;const association=associate(text,t);const duplicate=templates.has(normalized(p.text));templates.add(normalized(p.text));if(at<(t.xWindowStart??t.enrolledAt))continue;const post={id:p.id,ca:t.ca,author:p.author_id,text:p.text,at,receivedAt,association,duplicate,url:`https://x.com/i/status/${p.id}`};if(s.post(post)&&classifyPost(post,before).weight===1&&association!=='ambiguous')currentAuthors.add(p.author_id);}
   s.db.prepare('DELETE FROM charges WHERE day=? AND id=?').run(new Date(now).toISOString().slice(0,10),reserveId);const n=s.get('token',t.ca);const observation=xObservation(before,s.posts(t.ca),receivedAt,!j.meta?.next_token,!before.some(p=>p.association!=='ambiguous'&&!p.duplicate));const boost=observation.newAuthors>0&&!n.xBoostStartedAt?{xBoostStartedAt:receivedAt,xBoostUntil:receivedAt+180000}:{};s.put('token',t.ca,{...n,...boost,xReservedCost:0,xNewAuthorAt:observation.newAuthors?receivedAt:n.xNewAuthorAt,xObservations:[...(n.xObservations??[]).filter(o=>o.at>=receivedAt-1800000),observation].slice(-200),cost:Math.max(0,n.cost-max*r.postPrice+uniqueCost),lastXAt:receivedAt,xNext:j.meta?.next_token??undefined,xPendingNewest:j.meta?.next_token?(t.xPendingNewest??j.meta?.newest_id):undefined,xSince:j.meta?.next_token?t.xSince:(t.xPendingNewest??j.meta?.newest_id??t.xSince),lastSignalAt:currentAuthors.size?now:n.lastSignalAt});this.status.x='已连接 · 增量搜索';
  }catch(e){
   const rejected=[400,401,402,403,422,429].includes(e.status)||e.code==='X_WINDOW_NOT_READY';
   if(rejected){s.db.prepare('DELETE FROM charges WHERE day=? AND id=?').run(new Date(now).toISOString().slice(0,10),reserveId);const n=s.get('token',t.ca);if(n)s.put('token',t.ca,{...n,xReservedCost:0,cost:Math.max(0,n.cost-max*r.postPrice)});s.event('budget','X 明确拒绝请求，释放本次内部预算预留（实际费用以 X 账单为准）',t.ca);}else{const n=s.get('token',t.ca);if(n)s.put('token',t.ca,{...n,xReservedCost:0});}   if([400,401,402,403,422].includes(e.status)){const message='X '+e.status+' · '+(e.problem??'请求被拒绝')+'，已暂停；排查配置后手动重试';s.put('config','x-block',{at:now,status:e.status,message});this.status.x=message;s.event('x',message,t.ca);}
   else{this.status.x='X '+(e.status??'网络')+' 错误，已退避';this.xBackoff=Date.now()+Math.max(60000,(e.retryAfter??60)*1000);if(!rejected)s.event('budget','请求结果不确定，预算预留暂不释放；以 X 账单核对',t.ca);}
  }
 }
 async researchTick(){const tokens=this.s.all('token').filter(t=>t.status!=='archived'&&t.fdv>=100000).sort((a,b)=>(a.researchedAt??0)-(b.researchedAt??0));const t=tokens[0];if(!t)return;this.s.put('token',t.ca,{...t,researchedAt:Date.now()});const sigs=await this.rpc('getSignaturesForAddress',[t.pool,{limit:20}]);if(!sigs.length)return;const parsed=await jsonFetch(`https://api.helius.xyz/v0/transactions/?api-key=${encodeURIComponent(this.env.HELIUS_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transactions:sigs.filter(x=>!x.err).map(x=>x.signature)})});this.ingestTrades(parsed);}
 parseTrades(raw,grads){const tokens=this.s.researchTokens();const stonk=parseStonkSwap(raw,tokens,(mint,at)=>this.valuation.price(mint,at));const native=parseEnhanced(raw,grads).filter(t=>!tokens.some(x=>x.ca===t.ca&&x.source==='stonk'));return [...native,...stonk];}
 saveTrade(tr){this.s.db.prepare('DELETE FROM records WHERE kind=? AND id=?').run('trade',tr.id+':'+tr.wallet+':'+tr.ca);this.s.put('trade',tr.id+':'+tr.wallet,tr);}
 ingestTrades(parsed){const grads=new Map(this.s.researchTokens().map(t=>[t.ca,t.graduatedAt]));const wallets=new Set();for(const tx of parsed){for(const tr of this.parseTrades(tx,grads)){this.saveTrade(tr);wallets.add(tr.wallet);}}for(const w of wallets)this.assess(w);}
 assess(wallet,context=null){const c=context??this.walletContext(),old=this.s.get('wallet',wallet),coverage=this.s.get('coverage',wallet),now=c.now;const tx=(c.byWallet.get(wallet)??[]).map(t=>({...t,graduatedAt:c.grads.get(t.ca)??t.graduatedAt}));const full=coverage?.parserVersion===3&&coverage?.complete===true&&!coverage?.unsupported&&!coverage?.queued&&now-(coverage?.checkedAt??0)<900000;const result=evaluateWallet(tx,c.rules,now,full,coverage?.firstActivityAt??(tx.length?tx.reduce((min,t)=>t.at>0&&t.at<=now?Math.min(min,t.at):min,Infinity):null),c.fees.get(wallet)??[]);const verifiedAt=result.status==='verified'?(old?.status==='verified'?(old.verifiedAt??now):now):null;this.s.put('wallet',wallet,{address:wallet,...result,verifiedAt,identifiedAt:old?.identifiedAt??now,updatedAt:now,scanQueued:coverage?.queued===true,scanError:coverage?.scanError??null,coverageNote:coverage?.unsupported?'存在未支持交易/转账，不能验证':full?'历史扫描完成；近 7 天 SOL 口径核验':`历史扫描 ${coverage?.pages??0} 页 · ${coverage?.capped?'已达安全上限，可继续扫描':'覆盖尚未完整'}`});if(!context)this.updateSmart(c.trades);}
 updateSmart(trades=null){const now=Date.now(),all=trades??this.s.all('trade');const wallets=new Map(this.s.all('wallet').filter(w=>w.status==='verified'&&w.verifiedAt).map(w=>[w.address,{...w,holding:new Set((w.positions??[]).filter(p=>p.remaining>0).map(p=>p.ca))}]));const stats=new Map();for(const tx of all){const w=wallets.get(tx.wallet);if(!w||tx.side!=='buy'||tx.at<w.verifiedAt||tx.at>now)continue;let row=stats.get(tx.ca);if(!row){row={bought:new Set(),holding:new Set(),fresh:new Set()};stats.set(tx.ca,row);}row.bought.add(tx.wallet);if(w.holding.has(tx.ca))row.holding.add(tx.wallet);if(now-tx.at<=300000)row.fresh.add(tx.wallet);}for(const t of this.s.all('token')){const row=stats.get(t.ca),bought=row?.bought.size??0,holding=row?.holding.size??0,fresh=row?.fresh.size??0;if(t.smartBought===bought&&t.smartHolding===holding&&t.smartNew===fresh&&!fresh)continue;this.s.put('token',t.ca,{...t,smartBought:bought,smartHolding:holding,smartNew:fresh,lastSignalAt:fresh?now:t.lastSignalAt});}} async scanWallet(wallet){if(this.walletScanning?.has(wallet))return this.s.get('wallet',wallet);if(!this.rpc)throw Error('请配置 Helius');if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(wallet))throw Error('钱包地址无效');const saved=this.s.get('coverage',wallet);const old=saved?.parserVersion===3?saved:{wallet,firstActivityAt:saved?.firstActivityAt,pages:0,unsupported:false,complete:false};this.s.put('coverage',wallet,{...old,parserVersion:3,wallet,queued:true,capped:false,pages:old?.pages??0,sessionPages:0});await this.scanWalletPage(wallet);return this.s.get('wallet',wallet);}
 async walletQueueTick(){const queue=this.s.all('coverage').filter(c=>c.queued).sort((a,b)=>(a.checkedAt??0)-(b.checkedAt??0));if(queue[0])await this.scanWalletPage(queue[0].wallet);else if(this.env.ENABLE_WALLET_RESEARCH==='true'){const candidate=this.s.all('wallet').filter(w=>!this.s.get('coverage',w.address)?.capped).sort((a,b)=>(this.s.get('coverage',a.address)?.checkedAt??0)-(this.s.get('coverage',b.address)?.checkedAt??0))[0];if(candidate&&Date.now()-(this.s.get('coverage',candidate.address)?.checkedAt??0)>300000)await this.scanWallet(candidate.address);}}
 async scanWalletPage(wallet){this.walletScanning??=new Set();if(this.walletScanning.has(wallet))return;this.walletScanning.add(wallet);try{await this.scanWalletPageInner(wallet);}catch(e){const c=this.s.get('coverage',wallet)??{wallet};this.s.put('coverage',wallet,{...c,checkedAt:Date.now(),scanError:'钱包历史请求失败，将重试',complete:false});this.assess(wallet);throw e;}finally{this.walletScanning.delete(wallet);}} async scanWalletPageInner(wallet){const c=this.s.get('coverage',wallet)??{wallet,pages:0,sessionPages:0};const u=new URL(`https://api.helius.xyz/v0/addresses/${wallet}/transactions`);u.searchParams.set('api-key',this.env.HELIUS_API_KEY);u.searchParams.set('limit','100');if(c.before)u.searchParams.set('before',c.before);const tx=await jsonFetch(u);if(!Array.isArray(tx))throw Error('钱包历史响应无效');const stop=c.complete?c.head:null;const stopIndex=stop?tx.findIndex(x=>x.signature===stop):-1;const rows=stopIndex>=0?tx.slice(0,stopIndex):tx;const grads=new Map(this.s.researchTokens().map(t=>[t.ca,t.graduatedAt]));let firstActivityAt=c.firstActivityAt??null;let unsupported=c.unsupported??false;for(const raw of rows){if(raw.feePayer===wallet&&Number.isFinite(Number(raw.fee))&&Number(raw.fee)>0&&(raw.transactionError||!this.parseTrades(raw,grads).some(t=>t.wallet===wallet)))this.s.put('wallet-fee',raw.signature+':'+wallet,{wallet,at:raw.timestamp*1000,sol:Number(raw.fee)/1e9});if(raw.transactionError)continue;const timestamp=raw.timestamp*1000;if(Number.isFinite(timestamp)&&timestamp>0&&timestamp<=Date.now())firstActivityAt=firstActivityAt===null?timestamp:Math.min(firstActivityAt,timestamp);const parsed=this.parseTrades(raw,grads).filter(t=>t.wallet===wallet);if(!parsed.length&&raw.type==='SWAP')unsupported=true;if(!parsed.length&&(raw.tokenTransfers??[]).some(t=>t.fromUserAccount===wallet||t.toUserAccount===wallet)){unsupported=true;for(const t of raw.tokenTransfers??[]){if(t.fromUserAccount!==wallet&&t.toUserAccount!==wallet)continue;this.s.put('trade',raw.signature+':'+wallet+':'+t.mint,{id:raw.signature,wallet,ca:t.mint,at:raw.timestamp*1000,side:'transfer',quantity:Math.abs(t.tokenAmount??0),sol:0,graduatedAt:grads.get(t.mint)??0,complete:false});}}for(const tr of parsed)this.saveTrade(tr);}
 const done=tx.length<100||stopIndex>=0;const pages=(c.sessionPages??0)+1;this.s.put('coverage',wallet,{...c,wallet,pages:(c.pages??0)+1,sessionPages:pages,parserVersion:3,scanError:null,firstActivityAt,unsupported,checkedAt:Date.now(),pendingHead:c.pendingHead??tx[0]?.signature,head:done?(c.pendingHead??tx[0]?.signature??c.head):c.head,before:done?undefined:tx.at(-1)?.signature,queued:!done&&pages<50,capped:!done&&pages>=50,complete:done||(c.complete??false),...(done?{pendingHead:undefined}:{} )});this.assess(wallet);}
}
