import test from 'node:test';
import assert from 'node:assert/strict';
import {newToken,defaults,transition,heat,validateRules,queryFor,associate,evaluatePosition,evaluateWallet} from '../lib/engine.ts';
import {Store} from '../backend/store.mjs';
import {decodeMigration,PUMP,parseEnhanced} from '../backend/providers.mjs';
import {Worker} from '../backend/worker.mjs';
const now=1800000000000;const token=()=>({...newToken('11111111111111111111111111111111','pool',now-600000,now-600000),marketAt:now,fdv:30000});
test('24h hard stop, including sleeping tokens',()=>{assert.equal(transition({...token(),graduatedAt:now-86400000,status:'sleeping'},defaults,now,0,99).status,'archived');});
test('single low tick does not exit; sustained low FDV does',()=>{const t={...token(),fdv:9999};assert.equal(transition(t,defaults,now,0,0).status,'observing');assert.equal(transition({...t,lowSince:now-180000},defaults,now,0,0).status,'sleeping');});
test('stale data cannot trigger low FDV exit; five minutes without data sleeps for data loss',()=>{const n=transition({...token(),fdv:1,marketAt:now-300000,lowSince:now-600000},defaults,now,0,0);assert.equal(n.status,'sleeping');assert.equal(n.reason,'行情缺失或过期超过 5 分钟，暂停 X');assert.equal(n.lowSince,null);});
test('wake preserves graduation and cost; respects cooldown and max wakes',()=>{const t={...token(),status:'sleeping',stateAt:now-1800000,highSince:now-300000,lastSignalAt:now,cost:.1};const n=transition(t,defaults,now,0,0);assert.equal(n.status,'observing');assert.equal(n.cost,.1);assert.equal(n.graduatedAt,t.graduatedAt);assert.equal(n.wakeCount,1);assert.equal(transition({...t,wakeCount:2},defaults,now,0,0).status,'sleeping');});
test('manual sleep does not automatically wake',()=>{assert.equal(transition({...token(),status:'sleeping',reason:'手动休眠',stateAt:now-1800000,highSince:now-600000},defaults,now,0,0).status,'sleeping');});
test('budget exhaustion forces sleep even for popular token',()=>{assert.equal(transition(token(),defaults,now,10,100).status,'sleeping');assert.equal(transition({...token(),cost:.5},defaults,now,0,100).status,'sleeping');});
test('rules reject >24h and nonfinite or impossible wallet thresholds',()=>{assert.throws(()=>validateRules({...defaults,maxAgeHours:25}));assert.throws(()=>validateRules({...defaults,dailyBudget:NaN}));assert.throws(()=>validateRules({...defaults,minSamples:1,minWins:3}));});
test('queries only expand after association is explicitly verified',()=>{const t={...token(),name:'Orbit',xAccount:'orbit'};assert(!queryFor(t).includes('Orbit'));assert(queryFor({...t,aliasVerified:true}).includes('Orbit'));assert.equal(associate('Orbit',t),'ambiguous');assert.equal(associate(t.ca,t),'exact');});
test('heat excludes future, duplicate, and ambiguous posts',()=>{const make=(id,at,more={})=>({id,at,text:'discussion '+String.fromCharCode(65+Number(id)),ca:'a',author:id,association:'exact',duplicate:false,...more});const h=heat([make('1',now-1000),make('2',now-2000,{duplicate:true}),make('3',now-3000,{association:'ambiguous'}),make('4',now+1000)],'a',now);assert.equal(h.authors,1);assert.equal(h.ambiguous,1);});
const trade=(id,side,minutes,quantity,sol,more={})=>({id,side,at:now+minutes*60000,quantity,sol,wallet:'w',ca:'c',graduatedAt:now,...more});
test('99% scalp plus dust tail is not long hold',()=>{const p=evaluatePosition([trade('1','buy',0,100,1),trade('2','sell',1,99,5),trade('3','sell',120,1,.1)],defaults,now+121*60000);assert.equal(p.qualifies,false);assert.equal(p.longFraction,.01);});
test('substantial long-held realized gains qualify',()=>{const p=evaluatePosition([trade('1','buy',0,100,1),trade('2','sell',40,80,4)],defaults,now+50*60000);assert(p.qualifies);assert.equal(p.multiple,5);assert.equal(p.remaining,20);});
test('unknown transfers prevent qualification',()=>{const p=evaluatePosition([trade('0','transfer',0,1,0),trade('1','buy',0,100,1),trade('2','sell',40,100,5)],defaults,now+50*60000);assert(!p.qualifies);assert(p.unknown);});
test('future trades cannot change an earlier wallet label',()=>{const p=evaluatePosition([trade('1','buy',0,100,1),trade('2','sell',40,100,5)],defaults,now+60000);assert.equal(p.multiple,null);assert(!p.qualifies);});
test('incomplete history never produces verified wallet',()=>{const rows=Array.from({length:10},(_,i)=>[trade('b'+i,'buy',0,100,1,{ca:String(i)}),trade('s'+i,'sell',40,100,4,{ca:String(i)})]).flat();assert.equal(evaluateWallet(rows,defaults,now+3600000,false,now-31*86400000).status,'candidate');assert.equal(evaluateWallet(rows,defaults,now+3600000,true,now-31*86400000).status,'verified');});
test('SQLite deduplicates posts and costs by UTC day',()=>{const s=new Store(':memory:');const p={id:'p',ca:'a',at:now};assert(s.post(p));assert(!s.post(p));assert(s.charge('p',.005,now));assert(!s.charge('p',.005,now));assert.equal(s.cost(now),.005);assert.equal(s.cost(now+86400000),0);s.close();});
test('migration event must come from active Pump invocation',()=>{const b=Buffer.alloc(200);Buffer.from([189,233,93,185,92,148,234,148]).copy(b);b.writeBigInt64LE(BigInt(now/1000),128);const log='Program data: '+b.toString('base64');assert.equal(decodeMigration([log]),null);assert.equal(decodeMigration(['Program fake invoke [1]',log]),null);assert.equal(decodeMigration([`Program ${PUMP} invoke [1]`,log]).graduatedAt,now);});
test('native swaps enforce wallet ownership and account for fees',()=>{const tx={signature:'sig',type:'SWAP',timestamp:now/1000,fee:5000,feePayer:'w',events:{swap:{nativeInput:{account:'w',amount:1e9},tokenOutputs:[{mint:'c',userAccount:'w',rawTokenAmount:{tokenAmount:'1000000',decimals:6}}]}}};assert.equal(parseEnhanced(tx,new Map([['c',now]]))[0].sol,1.000005);tx.events.swap.tokenOutputs[0].userAccount='other';assert.equal(parseEnhanced(tx,new Map()).length,0);});
test('missing credentials cause no paid request',async()=>{const s=new Store(':memory:');s.put('token',token().ca,token());const w=new Worker(s,{});await w.xPoll();assert.equal(s.cost(),0);assert.equal(w.status.x,'未配置');s.close();});
test('X request reserves maximum cost and refunds unused capacity',async()=>{const original=globalThis.fetch;const s=new Store(':memory:');const at=Date.now();const t={...newToken('11111111111111111111111111111111','pool',at-60000,at-60000)};Object.assign(t,{fdv:30000,lp:15000,marketAt:Date.now()});s.put('token',t.ca,t);const w=new Worker(s,{X_BEARER_TOKEN:'test',ENABLE_X:'true'});w.running=true;let requests=0;globalThis.fetch=async()=>{requests++;assert(s.cost()>=.49);return new Response(JSON.stringify({data:[{id:'1',author_id:'a',created_at:new Date(at).toISOString(),text:t.ca}],meta:{newest_id:'1'}}),{status:200,headers:{'content-type':'application/json'}});};try{await w.xPoll();assert.equal(requests,1);assert(Math.abs(s.cost()-.005)<1e-9);assert(Math.abs(s.get('token',t.ca).cost-.005)<1e-9);}finally{globalThis.fetch=original;s.close();}});
test('uncertain X failure retains reserve and prevents immediate retry',async()=>{const original=globalThis.fetch;const s=new Store(':memory:');const at=Date.now();const t=newToken('11111111111111111111111111111111','pool',at-60000,at-60000);Object.assign(t,{fdv:30000,lp:15000,marketAt:Date.now()});s.put('token',t.ca,t);const w=new Worker(s,{X_BEARER_TOKEN:'test',ENABLE_X:'true'});w.running=true;let requests=0;globalThis.fetch=async()=>{requests++;throw Error('network');};try{await w.xPoll();await w.xPoll();assert.equal(requests,1);assert.equal(s.cost(),.5);}finally{globalThis.fetch=original;s.close();}});
test('X never calls API when minimum response capacity exceeds remaining budget',async()=>{const s=new Store(':memory:');const at=Date.now(),t={...newToken('11111111111111111111111111111111','pool',at-60000,at-60000),cost:.49};Object.assign(t,{fdv:30000,lp:15000,marketAt:Date.now()});s.put('token',t.ca,t);const w=new Worker(s,{X_BEARER_TOKEN:'test',ENABLE_X:'true'});w.running=true;await w.xPoll();assert.equal(s.cost(),0);assert.equal(s.get('token',t.ca).status,'sleeping');s.close();});


test('wallet age must strictly exceed 30 days even with profitable complete history',()=>{const rows=Array.from({length:10},(_,i)=>[trade('ab'+i,'buy',0,100,1,{ca:String(i)}),trade('as'+i,'sell',40,100,4,{ca:String(i)})]).flat();const t=now+3600000;for(const first of [null,t+1,t-29*86400000,t-30*86400000]){const w=evaluateWallet(rows,defaults,t,true,first);assert.equal(w.status,'watch');assert.equal(w.ageEligible,false);}assert.equal(evaluateWallet(rows,defaults,t,true,t-31*86400000).status,'verified');assert.equal(evaluateWallet(rows,{...defaults,minWalletAgeDays:40},t,true,t-31*86400000).status,'watch');});

test('wallet scan persists age evidence from non-swap chain activity',async()=>{const original=globalThis.fetch,s=new Store(':memory:');const w=new Worker(s,{HELIUS_API_KEY:'test'});const first=Date.now()-40*86400000;globalThis.fetch=async()=>new Response(JSON.stringify([{signature:'old',timestamp:Math.floor(first/1000),type:'TRANSFER',nativeTransfers:[],tokenTransfers:[]}]),{status:200});try{await w.scanWalletPage('11111111111111111111111111111111');assert.equal(s.get('coverage','11111111111111111111111111111111').firstActivityAt,Math.floor(first/1000)*1000);assert.equal(s.get('wallet','11111111111111111111111111111111').ageEligible,true);}finally{globalThis.fetch=original;s.close();}});
test('startup removes legacy verified labels without age evidence',()=>{const s=new Store(':memory:');s.put('wallet','old',{address:'old',status:'verified',verifiedAt:1});new Worker(s,{});assert.equal(s.get('wallet','old').status,'watch');assert.equal(s.get('wallet','old').verifiedAt,null);s.close();});
