import test from 'node:test';
import assert from 'node:assert/strict';
import {mintFee,parseStonkSwap,Valuation,SOL_MINT} from '../backend/valuation.mjs';
import {afterTax,executionReady} from '../lib/execution.ts';
import {buyFill,sellFill,shadowDefaults,newShadowRun,shadowStep} from '../lib/shadow.ts';
import {evaluateWallet,defaults} from '../lib/engine.ts';
import {Store} from '../backend/store.mjs';
import {Worker} from '../backend/worker.mjs';
const now=Date.now(),fee={bps:300,maxFee:1,decimals:6};
const mint=(extensions=[])=>({value:{owner:'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',data:{parsed:{info:{decimals:6,extensions}}}}});
test('transfer fee rounds up smallest units and obeys cap',()=>{assert.equal(afterTax(100,fee),99);assert.equal(afterTax(.000001,fee),0);assert.equal(afterTax(10,{...fee,bps:100}),9.9);assert(Number.isNaN(afterTax(10,{...fee,bps:10001})));});
test('mint taxes select current epoch and reject unsupported extensions',()=>{const config={extension:'transferFeeConfig',state:{olderTransferFee:{epoch:1,maximumFee:'1000000',transferFeeBasisPoints:100},newerTransferFee:{epoch:5,maximumFee:'2000000',transferFeeBasisPoints:300}}};assert.equal(mintFee(mint([config]),4).bps,100);assert.equal(mintFee(mint([config]),5).maxFee,2);assert.equal(mintFee(mint(),5).bps,0);assert.throws(()=>mintFee(mint([{extension:'transferHook'}]),5));});
function token(){return {ca:'c',symbol:'C',source:'stonk',status:'observing',priceUsd:1,lp:20000,fdv:100000,graduatedAt:now-60000,marketAt:now,execution:{at:now,priceAt:now,quotePriceUsd:10,baseFee:{bps:300,maxFee:100,decimals:6},quoteFee:{bps:100,maxFee:100,decimals:6}}};}
test('Shadow deducts both base and quote taxes, preserving source snapshots',()=>{const t=token(),plain=buyFill(1,20000,50,shadowDefaults),taxed=buyFill(1,20000,50,shadowDefaults,t);assert(taxed.quantity<plain.quantity);assert.equal(taxed.taxModel.baseFee.bps,300);assert(sellFill(1,20000,50,shadowDefaults,t).proceeds<sellFill(1,20000,50,shadowDefaults).proceeds);t.execution.baseFee.bps=999;assert.equal(taxed.taxModel.baseFee.bps,300);});
test('Stonk can enter Shadow; stale tax state prevents manufactured exits or values',()=>{const t=token(),social=new Map([['c',{authors:10,clean:20}]]);let s=shadowStep(newShadowRun(now),[t],social,new Map(),now);assert.equal(s.arms[0].positions[0].status,'pending');s=shadowStep(s,[{...t,marketAt:now+30000}],social,new Map(),now+30000);assert.equal(s.arms[0].positions[0].status,'open');assert(s.arms[0].positions[0].fills[0].taxModel);s=shadowStep(s,[{...t,marketAt:now+400000}],social,new Map(),now+400000);assert.equal(s.arms[0].equity,null);assert.equal(executionReady(t,now-1),false);});
const tracked=[{ca:'c',quoteMint:'q',source:'stonk',graduatedAt:now-60000}];
const delta=(mint,n)=>({userAccount:'w',mint,rawTokenAmount:{tokenAmount:String(n*1e6),decimals:6}});
function tx(){return {signature:'sig',type:'SWAP',timestamp:Math.floor(now/1000),feePayer:'w',fee:5000,accountData:[{tokenBalanceChanges:[delta('c',97),delta('q',-2)]}]};}
test('wallet uses net balance deltas and contemporaneous FX without double tax',()=>{const [t]=parseStonkSwap(tx(),tracked,m=>m===SOL_MINT?100:10);assert.equal(t.quantity,97);assert.equal(t.currency,'USD');assert.equal(t.value,20.0005);assert.equal(t.complete,true);const sell=tx();sell.accountData[0].tokenBalanceChanges=[delta('c',-97),delta('q',8)];const [s]=parseStonkSwap(sell,tracked,m=>m===SOL_MINT?100:10);assert.equal(s.value,79.9995);assert.equal(s.side,'sell');});
test('missing FX keeps transaction but cannot qualify; multi-asset and third-party wallet are excluded',()=>{assert.equal(parseStonkSwap(tx(),tracked,()=>null)[0].complete,false);const extra=tx();extra.accountData[0].tokenBalanceChanges.push(delta('other',2));assert.equal(parseStonkSwap(extra,tracked,()=>10).length,0);const sponsored=tx();sponsored.feePayer='sponsor';assert.equal(parseStonkSwap(sponsored,tracked,()=>10).length,0);});
test('FX lookup never substitutes future or stale prices',()=>{const s=new Store(':memory:'),v=new Valuation({s});s.put('fx','future',{mint:'q',at:now+1,usd:100});s.put('fx','old',{mint:'q',at:now-120001,usd:50});assert.equal(v.price('q',now),null);s.put('fx','valid',{mint:'q',at:now-1000,usd:10});assert.equal(v.price('q',now),10);s.close();});
test('USD winners can qualify with wallet age and size gates; SOL losses cannot be hidden by USD gains',()=>{const trades=[];for(let i=0;i<10;i++)trades.push({id:'b'+i,wallet:'w',ca:'c'+i,side:'buy',quantity:100,sol:0,value:20,currency:'USD',at:now-3600000,graduatedAt:now-3610000,complete:true},{id:'s'+i,wallet:'w',ca:'c'+i,side:'sell',quantity:100,sol:0,value:80,currency:'USD',at:now-600000,graduatedAt:now-3610000,complete:true});const w=evaluateWallet(trades,defaults,now,true,now-40*86400000);assert.equal(w.status,'verified');assert.equal(w.profit,0);assert.equal(w.profitUsd,600);assert.equal(evaluateWallet(trades,defaults,now,true,now-86400000).status,'watch');trades.push({id:'lossb',wallet:'w',ca:'loss',side:'buy',quantity:1,sol:100,at:now-3600000,graduatedAt:now-3610000},{id:'losss',wallet:'w',ca:'loss',side:'sell',quantity:1,sol:1,at:now-600000,graduatedAt:now-3610000});assert.notEqual(evaluateWallet(trades,defaults,now,true,now-40*86400000).status,'verified');});
test('verified wallet Stonk buys are counted only after label was known',()=>{const s=new Store(':memory:'),w=new Worker(s,{});s.put('token','c',{ca:'c',source:'stonk'});s.put('wallet','w',{address:'w',status:'verified',verifiedAt:now-1000,positions:[{ca:'c',remaining:97}]});s.put('trade','x',{wallet:'w',ca:'c',side:'buy',at:now});w.updateSmart();assert.equal(s.get('token','c').smartBought,1);assert.equal(s.get('token','c').smartHolding,1);s.close();});
test('valuation batches mint checks and unblocks existing Stonk tokens with known taxes and FX',async()=>{const original=globalThis.fetch,s=new Store(':memory:'),w=new Worker(s,{});s.put('token','c',{...token(),execution:null,quoteMint:'q',shadowBlocked:'legacy block'});let batches=0;w.rpc=async(method,args)=>{if(method==='getEpochInfo')return {epoch:5};assert.equal(method,'getMultipleAccounts');batches++;return {value:args[0].map(()=>mint().value)};};globalThis.fetch=async()=>new Response(JSON.stringify(['q',SOL_MINT].map(address=>({chainId:'solana',pairAddress:'pool',baseToken:{address},priceUsd:'10',liquidity:{usd:10000}}))));try{await w.valuation.tick();assert.equal(batches,1);const t=s.get('token','c');assert.equal(t.shadowBlocked,null);assert.equal(t.execution.epoch,5);assert.equal(t.execution.quoteFee.bps,0);assert(executionReady(t,Date.now()));}finally{globalThis.fetch=original;s.close();}});

test('missing USD valuation prevents verified status despite other profitable samples',()=>{const trades=[];for(let i=0;i<10;i++)trades.push({id:'b'+i,wallet:'w',ca:'c'+i,side:'buy',quantity:100,sol:1,at:now-3600000,graduatedAt:now-3610000},{id:'s'+i,wallet:'w',ca:'c'+i,side:'sell',quantity:100,sol:4,at:now-600000,graduatedAt:now-3610000});trades.push({id:'unknown',wallet:'w',ca:'u',side:'buy',quantity:10,sol:0,currency:'USD',value:null,complete:false,at:now-60000,graduatedAt:now-70000});const w=evaluateWallet(trades,defaults,now,true,now-40*86400000);assert.equal(w.unknownPositions,1);assert.notEqual(w.status,'verified');assert.equal(w.positions.find(p=>p.ca==='u').remaining,10);});
