import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../backend/store.mjs';
import {Worker} from '../backend/worker.mjs';
import {newToken} from '../lib/engine.ts';
import {recentX,jsonFetch} from '../backend/providers.mjs';

function setup(age=60000){const s=new Store(':memory:');const now=Date.now();const t=newToken('11111111111111111111111111111111','pool',now-age,now-age);s.put('token',t.ca,t);const env={X_BEARER_TOKEN:'test-secret',ENABLE_X:'true'};const w=new Worker(s,env);w.running=true;return {s,t,w,env};}
test('new enrollment and wake wait without fetching or reserving budget',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('must not fetch');};const {s,t,w}=setup(2000);try{await w.xPoll();assert.equal(s.cost(),0);assert.equal(s.get('token',t.ca).xLastPoll,undefined);await assert.rejects(recentX('test',t,t.ca,10),{code:'X_WINDOW_NOT_READY'});s.put('token',t.ca,{...t,enrolledAt:Date.now()-60000,xWindowStart:Date.now()});await w.xPoll();assert.equal(s.cost(),0);}finally{globalThis.fetch=original;s.close();}});
test('X timestamps use whole seconds; pagination keeps the same start and since_id excludes start_time',async()=>{const original=globalThis.fetch;const start=Date.now()-60000;const urls=[];globalThis.fetch=async url=>{urls.push(new URL(url));return new Response('{}');};try{await recentX('test',{enrolledAt:start},'ca',10);await recentX('test',{enrolledAt:start,xNext:'cursor'},'ca',10);await recentX('test',{enrolledAt:start,xSince:'123'},'ca',10);assert.match(urls[0].searchParams.get('start_time'),/T\d\d:\d\d:\d\dZ$/);assert(Date.parse(urls[0].searchParams.get('start_time'))>=start);assert.equal(urls[0].searchParams.get('start_time'),urls[1].searchParams.get('start_time'));assert.equal(urls[2].searchParams.has('start_time'),false);}finally{globalThis.fetch=original;}});
for(const status of [400,401,402,403,422])test(`X ${status} refunds reserve and persists pause across restart until explicit resume`,async()=>{const original=globalThis.fetch;const {s,t,w,env}=setup();let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({detail:'start_time test-secret'}),{status});};try{await w.xPoll();assert.equal(s.cost(),0);assert.equal(s.get('token',t.ca).cost,0);assert(s.get('config','x-block'));const restarted=new Worker(s,env);restarted.running=true;await restarted.xPoll();assert.equal(calls,1);assert(!JSON.stringify(s.all('event')).includes('test-secret'));restarted.resumeX();s.put('token',t.ca,{...s.get('token',t.ca),xLastPoll:0});await restarted.xPoll();assert.equal(calls,2);}finally{globalThis.fetch=original;s.close();}});
test('429 refunds reserve and respects rate reset without auth pause',async()=>{const original=globalThis.fetch;const {s,w}=setup();let calls=0;const reset=Math.ceil(Date.now()/1000)+300;globalThis.fetch=async()=>{calls++;return new Response('{}',{status:429,headers:{'x-rate-limit-reset':String(reset)}});};try{await w.xPoll();await w.xPoll();assert.equal(calls,1);assert.equal(s.cost(),0);assert.equal(s.get('config','x-block'),null);assert(w.xBackoff>=reset*1000-1000);}finally{globalThis.fetch=original;s.close();}});
test('503 keeps uncertain reserve and does not invent successful collection',async()=>{const original=globalThis.fetch;const {s,t,w}=setup();globalThis.fetch=async()=>new Response('{}',{status:503});try{await w.xPoll();assert.equal(s.cost(),.5);assert(!s.get('token',t.ca).lastXAt);}finally{globalThis.fetch=original;s.close();}});
test('Retry-After HTTP dates produce finite retry delay',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('{}',{status:429,headers:{'retry-after':new Date(Date.now()+120000).toUTCString()}});try{await assert.rejects(jsonFetch('https://example.test'),e=>e.retryAfter>110&&e.retryAfter<=120);}finally{globalThis.fetch=original;}});
