import { socialWindow } from './social.ts';
export type Status = 'observing' | 'priority' | 'sleeping' | 'archived';
export interface Rules { maxAgeHours:number; lowFdv:number; lowMinutes:number; wakeFdv:number; wakeMinutes:number; idleMinutes:number; initialMinutes:number; lateHours:number; lateAuthors:number; maxWakes:number; cooldownMinutes:number; dailyBudget:number; tokenBudget:number; postPrice:number; maxActive:number; holdMinutes:number; holdFraction:number; earlyMinutes:number; minMultiple:number; minInvestSol:number; minSamples:number; minWins:number; minWalletAgeDays:number }
export const defaults:Rules={maxAgeHours:24,lowFdv:10000,lowMinutes:3,wakeFdv:15000,wakeMinutes:5,idleMinutes:30,initialMinutes:60,lateHours:12,lateAuthors:5,maxWakes:2,cooldownMinutes:15,dailyBudget:10,tokenBudget:0.5,postPrice:0.005,maxActive:100,holdMinutes:30,holdFraction:0.5,earlyMinutes:10,minMultiple:3,minInvestSol:0.1,minSamples:10,minWins:3,minWalletAgeDays:30};
export interface Token { ca:string; symbol:string; name:string; pool:string; graduatedAt:number; enrolledAt:number; status:Status; reason:string; fdv:number|null; lp:number|null; holders:number|null; marketAt:number|null; marketError?:string|null; holdersAt?:number; xAccount:string|null; aliasVerified:boolean; cost:number; wakeCount:number; stateAt:number; lowSince:number|null; highSince:number|null; lastSignalAt:number; lastXAt:number|null; xSince?:string; xWindowStart?:number; xNext?:number; smartBought:number; smartHolding:number; smartNew:number; history:{at:number;fdv:number;authors:number}[] }
export interface Post { id:string; ca:string; author:string; text:string; at:number; receivedAt:number; association:'exact'|'name'|'ambiguous'; duplicate:boolean; url:string }
export function newToken(ca:string, pool:string, graduatedAt:number, now=Date.now()):Token {return {ca,pool,symbol:ca.slice(0,5),name:'等待代币资料',graduatedAt,enrolledAt:now,status:'observing',reason:'初始观察',fdv:null,lp:null,holders:null,marketAt:null,xAccount:null,aliasVerified:false,cost:0,wakeCount:0,stateAt:now,lowSince:null,highSince:null,lastSignalAt:now,lastXAt:null,smartBought:0,smartHolding:0,smartNew:0,history:[]};}
export function validateRules(input:unknown):Rules { const v=input as Rules;if(!v||typeof v!=='object')throw Error('规则格式不正确');for(const k of Object.keys(defaults) as (keyof Rules)[]){if(!Number.isFinite(v[k])||v[k]<0)throw Error(`${k} 必须为非负数字`);}if(v.maxAgeHours<=0||v.maxAgeHours>24)throw Error('最大 AGE 必须大于 0 且不超过 24 小时');if(v.wakeFdv<=v.lowFdv)throw Error('唤醒 FDV 必须高于退出 FDV');if(v.holdFraction<=0||v.holdFraction>1)throw Error('实质持仓比例必须介于 0 和 1');if(v.postPrice<=0||v.minSamples<1||v.minWins<1||v.minWins>v.minSamples||v.maxActive<1||v.maxActive>1000)throw Error('预算单价、钱包样本数或监控上限不正确');return Object.fromEntries(Object.keys(defaults).map(k=>[k,v[k as keyof Rules]])) as unknown as Rules;}
export function transition(t:Token,r:Rules,now:number,dayCost:number,authors:number):Token {
 const n={...t}; const age=(now-t.graduatedAt)/3600000;const fresh=!t.marketError&&t.marketAt!==null&&now>=t.marketAt&&now-t.marketAt<(t.status==='sleeping'?180000:120000);const set=(s:Status,reason:string)=>{if(n.status!==s){n.stateAt=now;n.lowSince=null;n.highSince=null;}n.status=s;n.reason=reason;return n;};
 if(age>=Math.min(24,r.maxAgeHours))return set('archived','达到最大 AGE');if(t.status==='archived')return n;
 if(t.cost+r.postPrice>r.tokenBudget)return set('sleeping','单币 X 预算上限');if(dayCost+r.postPrice>r.dailyBudget)return set('sleeping','今日 X 预算上限');
 if(!fresh){n.lowSince=null;n.highSince=null;if(t.reason!=='手动休眠'&&now-(t.marketAt??t.enrolledAt)>=300000)return set('sleeping','行情缺失或过期超过 5 分钟，暂停 X');}else{n.lowSince=t.fdv!==null&&t.fdv<r.lowFdv?(t.lowSince??now):null;n.highSince=t.fdv!==null&&t.fdv>=r.wakeFdv?(t.highSince??now):null;}
 if(t.status==='sleeping'){
  if(t.reason==='行情缺失或过期超过 5 分钟，暂停 X'&&fresh&&t.fdv!==null){if(t.fdv<r.lowFdv)return set('sleeping','FDV 低于下限，继续休眠');n.xWindowStart=now;n.xSince=undefined;n.xNext=undefined;return set('observing','行情恢复，继续观察');}
  if(t.reason==='手动休眠'||t.wakeCount>=r.maxWakes||now-t.stateAt<r.cooldownMinutes*60000)return n;
  if(n.highSince!==null&&now-n.highSince>=r.wakeMinutes*60000&&now-t.lastSignalAt<10*60000){n.wakeCount++;n.lastSignalAt=now;n.xWindowStart=now;n.xSince=undefined;return set('observing','链上信号重新唤醒');}return n;
 }
 if(n.lowSince!==null&&now-n.lowSince>=r.lowMinutes*60000)return set('sleeping','FDV 持续低于下限');
 if(age*60>=r.initialMinutes&&now-t.lastSignalAt>=r.idleMinutes*60000)return set('sleeping','讨论与链上信号持续无增长');
 if(age>=r.lateHours&&authors<r.lateAuthors&&now-t.lastSignalAt>10*60000)return set('sleeping','长龄币未达到活跃要求');
 return set(authors>=r.lateAuthors||t.smartNew>0?'priority':'observing',authors>=r.lateAuthors?'讨论扩散中':t.smartNew>0?'聪明钱包新买入':'观察中');
}
export function heat(posts:Post[],ca:string,now:number){const w=socialWindow(posts.filter(p=>p.ca===ca),now,5);const eligible=w.classified.filter(p=>p.association!=='ambiguous'&&p.quality.weight===1);const prior=new Set(eligible.filter(p=>p.at<=now-300000).map(p=>p.author));const previous=new Set(eligible.filter(p=>p.at>now-600000&&p.at<=now-300000).map(p=>p.author));const authors=new Set(w.eligible.map(p=>p.author));return {posts:w.clean,authors:w.authors,newAuthors:[...authors].filter(a=>!prior.has(a)).length,delta:authors.size-previous.size,duplicatePct:w.raw?Math.round(100*w.posts.filter(p=>p.quality.category==='duplicate').length/w.raw):0,filtered:w.filtered,raw:w.raw,ambiguous:w.posts.filter(p=>p.association==='ambiguous').length};}
export function queryFor(t:Token){const safe=(s:string)=>s.replace(/["\\\r\n]/g,' ').trim().slice(0,70);let q=`"${t.ca}"`;if(t.aliasVerified&&t.name.length>2&&t.xAccount)q+=` OR ("${safe(t.name)}" @${safe(t.xAccount).replace(/[^a-zA-Z0-9_]/g,'')})`;return `(${q}) -is:retweet`;}
export function associate(text:string,t:Token):Post['association'] {if(text.includes(t.ca))return 'exact';if(t.aliasVerified&&t.xAccount&&text.toLowerCase().includes(t.name.toLowerCase())&&text.toLowerCase().includes('@'+t.xAccount.toLowerCase()))return 'name';return 'ambiguous';}
export interface Trade {id:string;wallet:string;ca:string;at:number;side:'buy'|'sell'|'transfer';quantity:number;sol:number;graduatedAt:number;complete?:boolean}
export function evaluatePosition(trades:Trade[],r:Rules,now:number){const tx=trades.filter(t=>t.at<=now).sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id));let cost=0,proceeds=0,soldCost=0,bought=0,heldLong=0,unknown=false;const lots:{qty:number;cost:number;at:number}[]=[];let first=Infinity;let grad=Infinity;
 for(const t of tx){if(t.side==='transfer'||t.complete===false){unknown=true;continue;}if(t.side==='buy'){cost+=t.sol;bought+=t.quantity;lots.push({qty:t.quantity,cost:t.sol,at:t.at});first=Math.min(first,t.at);grad=Math.min(grad,t.graduatedAt);}else{let q=t.quantity;proceeds+=t.sol;while(q>1e-9&&lots.length){const l=lots[0];const take=Math.min(q,l.qty);const c=l.cost*(take/l.qty);soldCost+=c;if(t.at-l.at>=r.holdMinutes*60000)heldLong+=take;l.cost-=c;l.qty-=take;q-=take;if(l.qty<=1e-9)lots.shift();}if(q>1e-6)unknown=true;}}
 for(const l of lots)if(now-l.at>=r.holdMinutes*60000)heldLong+=l.qty;const remaining=lots.reduce((a,l)=>a+l.qty,0);const multiple=soldCost>0?proceeds/soldCost:null;const longFraction=bought?heldLong/bought:0;const early=Number.isFinite(first)&&first<=grad+r.earlyMinutes*60000;const closed=bought>0&&remaining<=bought*0.01;const qualifies=!unknown&&early&&cost>=r.minInvestSol&&longFraction>=r.holdFraction&&multiple!==null&&multiple>=r.minMultiple&&bought-remaining>=bought*r.holdFraction;return {cost,proceeds,soldCost,realizedProfit:proceeds-soldCost,multiple,longFraction,remaining,early,closed,unknown,qualifies};}
export function evaluateWallet(trades:Trade[],r:Rules,now:number,coverageComplete=false,firstActivityAt:number|null=null){const groups=Map.groupBy(trades,t=>t.ca);const positions=[...groups].map(([ca,tx])=>({ca,...evaluatePosition(tx,r,now)}));const samples=positions.filter(p=>p.closed&&!p.unknown).length;const wins=positions.filter(p=>p.qualifies).length;const profit=positions.reduce((s,p)=>s+(p.unknown?0:p.realizedProfit),0);const known=typeof firstActivityAt==='number'&&Number.isFinite(firstActivityAt)&&firstActivityAt>0&&firstActivityAt<=now;const walletAgeDays=known?(now-firstActivityAt!)/86400000:null;const ageEligible=walletAgeDays!==null&&walletAgeDays>r.minWalletAgeDays;return {positions,samples,wins,profit,firstActivityAt:known?firstActivityAt:null,walletAgeDays,ageEligible,ageReason:!known?'链上年龄未知':!ageEligible?'链上年龄未超过门槛':'链上年龄符合要求',status:ageEligible&&coverageComplete&&samples>=r.minSamples&&wins>=r.minWins&&profit>0?'verified':ageEligible&&wins>0?'candidate':'watch',coverageComplete};}
