import {afterTax,executionReady} from './execution.ts';
export const SHADOW_VERSION='shadow-v3';
export const shadowDefaults={positionUsd:50,initialCash:1000,minFdv:20000,maxFdv:2500000,minLp:15000,maxAgeHours:12,minAuthors:5,minPosts:10,aiScore:65,maxRisk:40,minConfidence:.6,stopLoss:.25,partialTake:2,partialFraction:.5,trailingDrop:.3,maxHoldHours:6,latencyMs:15000,slippage:.01,fee:.0125,fixedCostUsd:.05};
export type ShadowRules=typeof shadowDefaults;
export function validateShadowRules(v:any):ShadowRules{for(const [k,n]of Object.entries(shadowDefaults)){if(!Number.isFinite(v?.[k])||v[k]<0)throw Error('Shadow 参数无效：'+k);}if(v.maxAgeHours>24||v.maxAgeHours<=0||v.positionUsd<=0||v.initialCash<v.positionUsd||v.stopLoss<=0||v.stopLoss>=1||v.trailingDrop<=0||v.trailingDrop>=1||v.partialFraction<=0||v.partialFraction>=1||v.partialTake<=1||v.slippage>=.5||v.fee>=.2||v.minFdv>=v.maxFdv||v.minConfidence>1||v.aiScore>100||v.maxRisk>100)throw Error('Shadow 参数范围无效');return Object.fromEntries(Object.keys(shadowDefaults).map(k=>[k,v[k]])) as ShadowRules;}
export function entryGate(t:any,social:any,ai:any,arm:string,r:ShadowRules,now:number){if(t.shadowBlocked||t.marketError||!executionReady(t,now))return false;if(!['observing','priority'].includes(t.status))return false;if(!(t.priceUsd>0)||!(t.lp>=r.minLp)||!(t.fdv>=r.minFdv&&t.fdv<=r.maxFdv)||!t.marketAt||now-t.marketAt>60000||now<t.marketAt||now-t.graduatedAt>r.maxAgeHours*3600000||now<t.graduatedAt)return false;if(social.authors<r.minAuthors||social.clean<r.minPosts)return false;if(arm==='baseline')return true;return !!ai&&ai.status==='ok'&&ai.at<=now&&now-ai.at<=600000&&ai.overall>=r.aiScore&&ai.overall!==null&&ai.confidence>=r.minConfidence&&ai.dimensions.manipulationRisk.score!==null&&ai.dimensions.manipulationRisk.score<=r.maxRisk;}
// Synthetic constant-product impact estimate; NOT an executable DEX quote.
export function buyFill(price:number,lp:number,usd:number,r:ShadowRules,t?:any){const e=t?.source==='stonk'?t.execution:null;const net=(usd-r.fixedCostUsd)*(1-r.fee);if(net<=0)return null;const effective=e?afterTax(net/e.quotePriceUsd,e.quoteFee)*e.quotePriceUsd:net;const impact=effective/(lp/2+effective);const gross=effective/price*(1-impact)/(1+r.slippage);const quantity=e?afterTax(gross,e.baseFee):gross;return {quantity,price:usd/quantity,impact,taxModel:e?structuredClone(e):null};}
export function sellFill(price:number,lp:number,quantity:number,r:ShadowRules,t?:any){const e=t?.source==='stonk'?t.execution:null;const gross=(e?afterTax(quantity,e.baseFee):quantity)*price;const impact=gross/(lp/2+gross);const beforeTax=gross*(1-impact)*(1-r.slippage)*(1-r.fee);const proceeds=Math.max(0,(e?afterTax(beforeTax/e.quotePriceUsd,e.quoteFee)*e.quotePriceUsd:beforeTax)-r.fixedCostUsd);return {proceeds,price:quantity?proceeds/quantity:0,impact,taxModel:e?structuredClone(e):null};}
export function exitSignal(p:any,t:any,r:ShadowRules,now:number){if(now>=t.graduatedAt+24*3600000)return {fraction:1,reason:'24h 强制退出'};if(now-p.openedAt>=r.maxHoldHours*3600000)return {fraction:1,reason:'最大持仓时间'};if(t.status==='sleeping'||t.status==='archived')return {fraction:1,reason:'监控退出'};const multiple=t.priceUsd/p.entryReference;if(multiple<=1-r.stopLoss)return {fraction:1,reason:'止损'};if(!p.partialTaken&&multiple>=r.partialTake)return {fraction:r.partialFraction,reason:'分批止盈'};if(p.partialTaken&&t.priceUsd<=p.highPrice*(1-r.trailingDrop))return {fraction:1,reason:'跟踪止盈'};return null;}
export function shadowStep(state:any,tokens:any[],socials:Map<string,any>,ais:Map<string,any>,now:number){const n=structuredClone(state),r=n.rules as ShadowRules;if(n.version!==SHADOW_VERSION){n.modelChanges=[...(n.modelChanges??[]),{at:now,from:n.version,to:SHADOW_VERSION,reason:'启用 Stonk 双边转账税模型'}];n.version=SHADOW_VERSION;}if(Object.hasOwn(n.rules,'maxPositions')){n.ruleChanges=[...(n.ruleChanges??[]),{at:now,change:'移除持仓数量上限',previousMaxPositions:n.rules.maxPositions}];delete n.rules.maxPositions;n.version=SHADOW_VERSION;}for(const arm of n.arms){for(const p of arm.positions){if(p.status==='closed'||p.status==='cancelled')continue;const t=tokens.find(t=>t.ca===p.ca);if(!t)continue;const fresh=executionReady(t,now)&&!t.shadowBlocked&&!t.marketError&&t.priceUsd>0&&t.lp>0&&t.marketAt<=now&&now-t.marketAt<=60000;if(p.status==='pending'){if(now-p.signalAt>300000){p.status='cancelled';p.reason='入场等待超时';continue;}if(!fresh||(t.marketAt<=p.signalAt||t.marketAt<p.signalAt+r.latencyMs))continue;if(!entryGate(t,socials.get(t.ca),ais.get(t.ca),arm.id,r,now)){p.status='cancelled';p.reason='下一快照条件失效';continue;}const fill=buyFill(t.priceUsd,t.lp,r.positionUsd,r,t);if(!fill||arm.cash<r.positionUsd){p.status='cancelled';p.reason='资金不足';continue;}Object.assign(p,{status:'open',quantity:fill.quantity,initialQuantity:fill.quantity,cost:r.positionUsd,openedAt:now,entryReference:t.priceUsd,highPrice:t.priceUsd,realized:0,received:0,fills:[{side:'buy',at:now,quoteAt:t.marketAt,...fill}],partialTaken:false});arm.cash-=r.positionUsd;}
 if(p.status!=='open')continue;if(p.pendingExit){if(!fresh||(t.marketAt<=p.pendingExit.at||t.marketAt<p.pendingExit.at+r.latencyMs)){p.unpriced=true;continue;}const qty=p.quantity*p.pendingExit.fraction;const fill=sellFill(t.priceUsd,t.lp,qty,r,t);const cost=p.cost*(qty/p.initialQuantity);p.quantity-=qty;p.received+=fill.proceeds;p.realized+=fill.proceeds-cost;arm.cash+=fill.proceeds;p.fills.push({side:'sell',at:now,quoteAt:t.marketAt,quantity:qty,reason:p.pendingExit.reason,...fill});p.reason=p.pendingExit.reason;p.partialTaken=true;p.pendingExit=null;p.unpriced=false;if(p.quantity<=p.initialQuantity*1e-9){p.status='closed';p.closedAt=now;continue;}}
 if(!fresh){p.unpriced=true;continue;}p.unpriced=false;p.highPrice=Math.max(p.highPrice,t.priceUsd);const exit=exitSignal(p,t,r,now);if(exit)p.pendingExit={...exit,at:now};p.markValue=sellFill(t.priceUsd,t.lp,p.quantity,r,t).proceeds;}
 const reserved=arm.positions.filter((p:any)=>p.status==='pending').length*r.positionUsd;let free=arm.cash-reserved;for(const t of tokens){if(n.acceptEntries===false)break;if(arm.positions.some((p:any)=>p.ca===t.ca))continue;if(free<r.positionUsd)break;if(entryGate(t,socials.get(t.ca),ais.get(t.ca),arm.id,r,now)){arm.positions.push({id:`${arm.id}:${t.ca}`,ca:t.ca,symbol:t.symbol,status:'pending',signalAt:now,reason:'等待延迟后的新行情',evidence:{social:structuredClone(socials.get(t.ca)),aiId:ais.get(t.ca)?.id??null},fills:[]});free-=r.positionUsd;}}
 const missing=arm.positions.some((p:any)=>p.status==='open'&&p.unpriced);const equity=missing?null:arm.cash+arm.positions.filter((p:any)=>p.status==='open').reduce((s:number,p:any)=>s+(p.markValue??0),0);if(equity!==null){arm.peak=Math.max(arm.peak??r.initialCash,equity);arm.maxDrawdown=Math.max(arm.maxDrawdown??0,1-equity/arm.peak);}arm.equity=equity;arm.updatedAt=now;}return n;}
export function newShadowRun(now:number,r=shadowDefaults){return {id:String(now),version:SHADOW_VERSION,startedAt:now,rules:{...r},status:'running',arms:['baseline','ai'].map(id=>({id,cash:r.initialCash,equity:r.initialCash,peak:r.initialCash,maxDrawdown:0,positions:[]}))};}
