export const FILTER_VERSION='social-v1';
type TextPost={id:string;author:string;text:string;at:number;receivedAt?:number;association?:string;duplicate?:boolean};
export function fingerprint(text:string){return text.toLowerCase().replace(/https?:\/\/\S+/g,' URL ').replace(/[1-9A-HJ-NP-Za-km-z]{32,44}/g,' CA ').replace(/\$[a-z][a-z0-9_]*/gi,' TOKEN ').replace(/\d[\d.,]*\s*[%kmb]?/gi,' N ').replace(/[\s\p{P}\p{S}]+/gu,' ').trim();}
export function classifyPost(p:TextPost,prior:TextPost[]=[]){if(typeof p.text!=='string'||!p.text.trim())return {category:'unknown',weight:0,reasons:['缺少正文'],version:FILTER_VERSION};const reasons:string[]=[];const metrics=[/\b(?:ath\s*(?:mc|mcap)?|market\s*cap|fdv)\s*[:$]/i,/\b(?:liq|liquidity)\s*[:$]/i,/\bholders\s*:/i,/\btop\s*10\s*:/i,/\bsnipers\s*:/i,/\bbot\s*degens\s*:/i].filter(r=>r.test(p.text)).length;const cta=/quick\s*buy|just\s+hit\s+.*radar|buy\s*now|快速买入/i.test(p.text);if(metrics>=3||(metrics>=2&&cta)){return {category:'broadcast',weight:0,reasons:['固定行情字段/雷达播报，不计入自主讨论'],version:FILTER_VERSION};}
 const fp=fingerprint(p.text);if(p.duplicate||prior.some(x=>x.id!==p.id&&x.at<=p.at&&fingerprint(x.text)===fp)){return {category:'duplicate',weight:0,reasons:['与已采集帖子模板相同'],version:FILTER_VERSION};}
 if(/(?:referral|ref=|referralCode|join.*vip|paid\s*call|入群|返佣|跟单链接)/i.test(p.text)){return {category:'promotion',weight:.25,reasons:['推广/引流线索，降权保留'],version:FILTER_VERSION};}
 reasons.push('未发现强模板线索；不代表已验证真人');return {category:'discussion',weight:1,reasons,version:FILTER_VERSION};}
export function socialWindow(posts:TextPost[],now:number,minutes=15){const observed=posts.filter(p=>p.at<=now&&(p.receivedAt??p.at)<=now).sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id));const seen=new Set<string>();const classified=observed.map(p=>{let quality=classifyPost(p);const fp=fingerprint(p.text??'');if(quality.weight>0&&seen.has(fp))quality={category:'duplicate',weight:0,reasons:['与已采集帖子模板相同'],version:FILTER_VERSION};seen.add(fp);return {...p,quality};});const recent=classified.filter(p=>p.at>now-minutes*60000);const clean=recent.filter(p=>p.association!=='ambiguous'&&p.quality.weight===1);return {raw:recent.length,clean:clean.length,authors:new Set(clean.map(p=>p.author)).size,filtered:recent.filter(p=>p.quality.weight===0).length,promotion:recent.filter(p=>p.quality.category==='promotion').length,posts:recent,eligible:clean,classified};}
export const dimensions=['sentiment','narrative','substance','community','manipulationRisk'] as const;
export function validateAssessment(raw:any,ids:Set<string>){if(!raw||typeof raw!=='object')throw Error('AI 输出不是对象');if(!Number.isFinite(raw.confidence)||raw.confidence<0||raw.confidence>1)throw Error('AI 置信度无效');if(typeof raw.summary!=='string'||!raw.summary.trim()||raw.summary.length>1600)throw Error('AI 摘要无效');const scores:any={};for(const key of dimensions){const x=raw.dimensions?.[key];if(!x||!(x.score===null||(Number.isFinite(x.score)&&x.score>=0&&x.score<=100))||!Array.isArray(x.evidenceIds)||x.evidenceIds.length>12||typeof x.reason!=='string'||x.reason.length>600)throw Error('AI 维度格式无效：'+key);if(x.score!==null&&!x.evidenceIds.length)throw Error('评分缺少证据：'+key);if(x.evidenceIds.some((id:unknown)=>typeof id!=='string'||!ids.has(id)))throw Error('AI 引用了未提供的帖子');scores[key]={score:x.score,reason:x.reason,evidenceIds:x.evidenceIds};}const values=dimensions.map(k=>scores[k].score);const overall=values.some(x=>x===null)?null:Math.round(Math.max(0,Math.min(100,scores.sentiment.score*.2+scores.narrative.score*.2+scores.substance.score*.3+scores.community.score*.3-scores.manipulationRisk.score*.3)));const quoteMatch=validateQuoteMatch(raw.quoteMatch,ids);return {summary:raw.summary,confidence:raw.confidence,dimensions:scores,overall,quoteMatch};}

export function validateQuoteMatch(x:any,ids:Set<string>){
 if(x==null)return {score:null,reason:'尚未分析配对叙事',evidenceIds:[]};
 if(!(x.score===null||(Number.isFinite(x.score)&&x.score>=0&&x.score<=100))||typeof x.reason!=='string'||x.reason.length>600||!Array.isArray(x.evidenceIds)||x.evidenceIds.length>12||x.evidenceIds.some((id:unknown)=>typeof id!=='string'||!ids.has(id))||(x.score!==null&&!x.evidenceIds.length))throw Error('配对叙事评分缺少有效证据');
 return {score:x.score,reason:x.reason,evidenceIds:x.evidenceIds};
}
